# 1. Cấu hình kết nối tới MySQL
# Lưu ý: Nếu ở Bước 1 bạn đặt tên database khác 'do_an_java' thì hãy sửa lại ở cuối đường dẫn dưới đây
spring.datasource.url=jdbc:mysql://localhost:3306/do_an_java?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true

# Tài khoản đăng nhập MySQL của bạn (Mặc định là root)
spring.datasource.username=root

# !!! QUAN TRỌNG: Bạn hãy sửa chữ 'mat_khau_mysql_cua_ban' thành mật khẩu phần mềm MySQL trên máy bạn !!!
spring.datasource.password=123456

# Khai báo sử dụng Driver của MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# 2. Cấu hình Hibernate (Tự động tạo bảng từ code Java vào MySQL)
# 'update' giúp tự động tạo bảng hoặc thêm cột mới mỗi khi bạn chạy dự án mà không làm mất dữ liệu cũ
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL dưới Terminal để bạn dễ theo dõi và chấm bài/báo cáo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Định nghĩa ngôn ngữ MySQL cho Hibernate hiểu
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

